// Real browser + CLI checks against a disposable document, never the person's preview.
import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, readFile, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { promisify } from "node:util";
import { createServer } from "vite";
import { fileSessionPlugin } from "../bin/session-plugin.ts";
import { readReview } from "../bin/review-store.ts";
const exec = promisify(execFile);
const scratch = await mkdtemp(join(tmpdir(), "konpeki-notes-"));
const path = join(scratch, "composition.json");
const artifacts = resolve(process.argv[2] ?? ".amp/in/artifacts/notes");
await mkdir(artifacts, { recursive: true });
await writeFile(path, await readFile("slides/introducing-konpeki/composition.json"));
const server = await createServer({ server: { host: "127.0.0.1", port: 0 }, plugins: [fileSessionPlugin({ compositionPath: path, token: "notes-test" })] });
const b = async (...args) => (await exec("agent-browser", ["--session", "notes-check", ...args])).stdout.trim();
const cli = async (...args) => JSON.parse((await exec(process.execPath, ["bin/konpeki.mjs", ...args])).stdout);
const check = (expression) => b("eval", `if(!(${expression}))throw Error(${JSON.stringify(expression)})`);
const wait = (expression) => b("wait", "--fn", expression);
const capture = async name => {
  await b("eval", "document.fonts.ready.then(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))))");
  await b("screenshot", join(artifacts, `${name}.png`));
};
try {
  await server.listen();
  await b("open", `http://127.0.0.1:${server.httpServer.address().port}/?session=notes-test`);
  await b("set", "viewport", "1556", "1030", "2");
  await wait("!!document.querySelector('#revision-note:not(:disabled)')");
  const tab = name => b("find", "role", "button", "click", "--name", name, "--exact");
  await tab("Notes");
  await b("dblclick", ".stage-meta h2");
  await b("fill", 'input[aria-label="Page name"]', "Undo isolation");
  await b("press", "Enter");
  await wait("!document.querySelector('#revision-note').disabled");
  await b("type", "#revision-note", "x");
  await b("press", "Control+z");
  await check("document.querySelector('.stage-meta h2').textContent==='Undo isolation' && document.querySelector('#revision-note').value===''");
  await b("press", "Control+Shift+z");
  await check("document.querySelector('#revision-note').value==='x' && document.querySelector('.stage-meta h2').textContent==='Undo isolation'");
  await b("fill", "#revision-note", "Preserve the introduction wording");
  await b("find", "role", "button", "click", "--name", "Add note", "--exact");
  await wait("document.querySelectorAll('.revision-note-list li').length===1");
  assert.equal((await readReview(path)).request, undefined, "Adding a note must not submit a build");
  await tab("Pages");
  await b("find", "role", "button", "click", "--name", "04/06 Keep the detail editable", "--exact");
  await tab("Notes");
  await b("find", "role", "button", "click", "--name", "Select Diagram", "--exact");
  await b("fill", "#revision-note", "Component draft");
  await tab("Pages");
  await check("!document.querySelector('#revision-note').checkVisibility()");
  await tab("Notes");
  await check("document.querySelector('#revision-note').value==='Component draft'");
  await b("click", ".stage-meta h2");
  await check("document.querySelector('#revision-note').value===''");
  await b("fill", "#revision-note", "Page draft");
  await b("find", "role", "button", "click", "--name", "Select Diagram", "--exact");
  await check("document.querySelector('#revision-note').value==='Component draft'");
  await b("press", "Enter");
  const point = JSON.parse(await b("eval", '(()=>{const r=document.querySelector("[data-vector-element=review-node]").getBoundingClientRect();return {x:r.x+12,y:r.y+12}})()'));
  await b("mouse", "move", String(Math.round(point.x)), String(Math.round(point.y)));
  await b("mouse", "down", "left");
  await b("mouse", "up", "left");
  await wait("document.querySelector('.revision-note-scope').textContent.includes('review-node')");
  await check("(() => { const buttons = [...document.querySelectorAll('.vector-actions button')]; const boxes = buttons.map(button => button.getBoundingClientRect()); return buttons.length === 3 && boxes.every(box => box.width >= 40 && box.height >= 40) && boxes.every(box => Math.abs(box.y - boxes[0].y) < 1) && buttons.every(button => button.scrollWidth <= button.clientWidth); })()");
  await b("fill", "#revision-note", "Use square corners; keep size and position");
  await b("find", "role", "button", "click", "--name", "Add note", "--exact");
  await wait("document.querySelectorAll('.revision-note-list li').length===2");
  await check("[...document.querySelectorAll('.revision-pin')].every(pin => [...document.querySelectorAll('.resize-handle')].every(handle => { const a = pin.getBoundingClientRect(); const b = handle.getBoundingClientRect(); return a.right <= b.left || a.left >= b.right || a.bottom <= b.top || a.top >= b.bottom; }))");
  await check("[...document.querySelectorAll('.resize-handle')].every(handle => { const rect = handle.getBoundingClientRect(); return document.elementFromPoint(rect.x + rect.width / 2, rect.y + rect.height / 2) === handle; })");
  const notes = (await readReview(path)).notes;
  assert.deepEqual(notes.map(n => [n.slideId, n.componentId, n.elementId]), [["introduction", undefined, undefined], ["editing", "editable-diagram", "review-node"]]);
  await tab("Pages");
  await b("click", ".revision-pin");
  await check("document.querySelector('.left-notes').checkVisibility() && !document.querySelector('.slide-list').checkVisibility()");
  await check("!document.querySelector('.right-panel .revision-notes')");
  await check("document.querySelector('.revision-note-scope').textContent.includes('review-node')");
  await capture("scoped-notes");
  await b("eval", `(async()=>{
    const {exportPagePNG}=await import('/src/lib/export-png.ts');
    const source=document.querySelector('.canvas');
    const first=new Uint8Array(await (await exportPagePNG(source,{width:1920,height:1080})).arrayBuffer());
    source.querySelectorAll('.revision-pin').forEach(n=>n.remove());
    const second=new Uint8Array(await (await exportPagePNG(source,{width:1920,height:1080})).arrayBuffer());
    if(first.length!==second.length||first.some((v,i)=>v!==second[i]))throw Error('Note pins changed the exported PNG');
  })()`);
  await b("reload");
  await wait("document.querySelectorAll('.revision-note-list li').length===2");
  await b("click", ".build-button");
  await wait("!!document.querySelector('.build-loading')");
  await b("reload");
  await wait("!!document.querySelector('.build-loading')");
  const request = await cli("wait", path);
  assert.equal(request.notes.length, 2);
  await wait("document.querySelector('.build-loading-card strong').textContent==='Agent working'");
  await capture("working");
  await cli("finish", path, request.id, "--status", "needs-clarification", "--message", "Only Review, or all nodes?");
  await wait("!document.querySelector('.build-loading')");
  await tab("Notes");
  await check("!document.querySelector('.revision-notes').textContent.includes('Only Review')");
  assert.equal((await readReview(path)).notes.filter(n => !n.resolved).length, 2);
  await capture("clarification");
  await b("click", ".build-button");
  await wait("!!document.querySelector('.build-loading')");
  const retry = await cli("wait", path);
  await cli("finish", path, retry.id, "--message", "Reviewed and confirmed");
  await wait("!document.querySelector('.build-loading') && !document.querySelector('.revision-note-list')");
  await check("!document.querySelector('.revision-notes').textContent.includes('Use square corners') && !document.querySelector('.revision-notes').textContent.includes('Reviewed and confirmed')");
  assert.equal((await readReview(path)).notes.filter(n => n.resolved).length, 2, "Resolved notes remain stored but are hidden");
  await capture("resolved");
  await b("click", ".build-button");
  await wait("!!document.querySelector('.build-loading')");
  await b("find", "role", "button", "click", "--name", "Cancel request", "--exact");
  await wait("!document.querySelector('.build-loading')");
  assert.equal((await readReview(path)).request.status, "failed");
  await b("set", "viewport", "1024", "768", "2");
  await capture("narrow-cancelled");
  await check("(()=>{const p=document.querySelector('.inspector-content');p.scrollTop=p.scrollHeight;return p.scrollHeight<=p.clientHeight||p.scrollTop>0})()");
  console.log("Revision notes OK: page/vector scopes, independent drafts, durable notes and pending build on reload, CLI claim, clarification, explicit no-op completion, cancellation.");
} finally {
  await b("close").catch(() => {});
  await server.close();
  await rm(scratch, { recursive: true, force: true });
}
